### ISSUE TITLE
Feed NOT working

### ISSUE THREAD

**Issue by frank087234** [Openeight/enigma2#3]
Downloading http://feed.openeight.de/6.5/7210s/3rdparty/Packages.gz.

wget: server returned error: HTTP/1.1 404 Not Found

Downloading http://feed.openeight.de/6.5/7210s/7210s/Packages.gz.

wget: server returned error: HTTP/1.1 404 Not Found
Downloading http://feed.openeight.de/6.5/7210s/7210s_3rdparty/Packages.gz.

wget: server returned error: HTTP/1.1 404 Not Found

Downloading http://feed.openeight.de/6.5/7210s/all/Packages.gz.

wget: server returned error: HTTP/1.1 404 Not Found
Downloading http://feed.openeight.de/6.5/7210s/mips32el/Packages.gz.

wget: server returned error: HTTP/1.1 404 Not Found

**Comment by xtrendmaster** [comment]
Yes feeds are temporary down at moment please be patient while we solve some issue

**Comment by frank087234** [comment]
FEED is still  DOWN!!!!
