### ISSUE TITLE
Enigma2 crash when set system time manually on XTDVBNTPTime plugin

### ISSUE THREAD

**Issue by opfans** [Openeight/enigma2#5]
My receiver is SF4008,using Openeight 20191018 image.It can not get the correct system time via start up channel. So i tried to set system time manually on XTDVBNTPTime plugin,it failed and enigma2 crashed .Plus,it can get  correct system time with setting start up channel on openatv images.
here log
Openeight Enigma2 crash log

crashdate=鍏?10鏈?19 07:30:18 2019
compiledate=Oct 13 2019
skin=SmartLiteFHD/skin.xml
sourcedate=2019-10-13
branch=master
rev=db82b2a
version=4
component=Enigma2

stbmodel=sf4008
stbmodel=ultimo
stbmodel=dm800se
kernelcmdline=root=/dev/mmcblk0p4 rootwait rw vmalloc=692m bmem=700m@324m
nimsockets=NIM Socket 0:
imageversion=box_type=sf4008
imageissue=openeight 6.7 %h

Traceback (most recent call last):
File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
File "/usr/lib/enigma2/python/Plugins/Extensions/ExtrasPanel/XTDVBNTPTime.py", line 150, in go
File "/usr/lib/enigma2/python/Plugins/Extensions/ExtrasPanel/XTDVBNTPTime.py", line 409, in init
NameError: global name 'InputBox' is not defined

**Comment by opfans** [comment]
show enigma2 crash log
Openeight Enigma2 crash log

crashdate=鍏?10鏈?19 07:30:18 2019
compiledate=Oct 13 2019
skin=SmartLiteFHD/skin.xml
sourcedate=2019-10-13
branch=master
rev=db82b2a
version=4
component=Enigma2

stbmodel=sf4008
stbmodel=ultimo
stbmodel=dm800se
kernelcmdline=root=/dev/mmcblk0p4 rootwait rw vmalloc=692m bmem=700m@324m
nimsockets=NIM Socket 0:
imageversion=box_type=sf4008
imageissue=openeight 6.7 %h


Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 49, in action
  File "/usr/lib/enigma2/python/Plugins/Extensions/ExtrasPanel/XTDVBNTPTime.py", line 150, in go
  File "/usr/lib/enigma2/python/Plugins/Extensions/ExtrasPanel/XTDVBNTPTime.py", line 409, in __init__
NameError: global name 'InputBox' is not defined

**Comment by atom89** [comment]
Hi opfans,

thank you for reporting the issue, i will have a look at it later today.
you can (also) report issues for openeight at the octagon forum: https://octagon-forum.eu/forums/allgemein.94/
and read about the latest developments of openeight

regards
atom89

**Comment by atom89** [comment]
The problem is solved, it should be ok after tomorrows software update.
commit: https://github.com/Openeight/enigma2/commit/04090a5f4a10d412751d047a08880b72270dd6b4

regards
atom89 (Smokey)
