### ISSUE TITLE
enigma2.bb:do_compile

### ISSUE THREAD

**Issue by elhawaryna** [Openeight/enigma2#9]
ERROR: Task (/home/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb:do_compile) failed with exit code '1'

**Comment by betacentauri** [comment]
Some lines above you should find the name of the log file. Open the log file and search for the real error and post it here. 

Which OS are you using?
Which branch of the build environment do you use? We use 4.3.

**Comment by betacentauri** [comment]
No answer, I close. You can nevertheless reopen/comment.

**Comment by elhawaryna** [comment]
> Some lines above you should find the name of the log file. Open the log file and search for the real error and post it here.
> 
> Which OS are you using?
> Which branch of the build environment do you use? We use 4.3.

Sorry for my delay, I used one of the branches in the building environment and found this problem and used branch 4.4 and there are no problems  I will do what I prefer outside the home
